# Generated by Django 3.1.7 on 2021-02-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('position', models.CharField(blank=True, max_length=75, null=True)),
                ('veteran_status', models.CharField(blank=True, max_length=1, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtranLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_notional_amount', models.FloatField()),
                ('sba_number', models.CharField(max_length=10)),
                ('loan_number', models.CharField(max_length=7)),
                ('entity_name', models.CharField(max_length=120)),
                ('ein', models.CharField(max_length=11)),
                ('funding_date', models.DateField()),
                ('forgive_payroll', models.FloatField()),
                ('naics_code', models.IntegerField()),
                ('ppp_loan_draw', models.IntegerField()),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('dba_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('forgive_fte_at_loan_application', models.IntegerField()),
                ('forgive_amount', models.FloatField()),
                ('forgive_fte_at_forgiveness_application', models.IntegerField()),
                ('forgive_covered_period_from', models.DateField()),
                ('forgive_covered_period_to', models.DateField()),
                ('forgive_2_million', models.BooleanField(default=False)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_name', models.CharField(max_length=50)),
                ('ez_form', models.BooleanField(default=False)),
                ('forgive_lender_confirmation', models.BooleanField()),
                ('forgive_lender_decision', models.IntegerField()),
                ('s_form', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LookupDisbursedPPPLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('bank_notional_amount', models.FloatField()),
                ('sba_number', models.CharField(max_length=50)),
                ('entity_name', models.CharField(max_length=75)),
                ('ein', models.CharField(max_length=11)),
                ('funding_date', models.DateField()),
                ('tin_type', models.IntegerField()),
                ('ppp_loan_draw', models.IntegerField()),
                ('forgive_eidl_amount', models.FloatField()),
                ('eidl_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(blank=True, max_length=1, null=True)),
                ('dem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_3508.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='ForgivenessDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('etranLoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_3508.etranloan')),
            ],
        ),
        migrations.AddField(
            model_name='demographics',
            name='etranLoan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='S_3508.etranloan'),
        ),
    ]
